/*
 * validator/core/types.h
 *
 * Defines the shared data structures for the Universal Validator.
 * These structures act as the contract between the Exchange Adapters
 * and the Validator Core (Engine/Auditor).
 */

#ifndef VALIDATOR_CORE_TYPES_H
#define VALIDATOR_CORE_TYPES_H

#include <stddef.h>
#include <stdint.h>
#include "trcache.h"

/*
 * Column Index Definitions
 * These constants map to the order of fields in 'val_candle_fields'.
 * Used for accessing column_arrays in the Auditor with explicit indices.
 */
enum {
	VAL_COL_OPEN = 0,
	VAL_COL_HIGH,
	VAL_COL_LOW,
	VAL_COL_CLOSE,
	VAL_COL_VOLUME,
	VAL_COL_EXCHANGE_TS,
	VAL_COL_LOCAL_TS,
	VAL_COL_START_SEQ_ID,
	VAL_COL_END_SEQ_ID,
	/* Sentinel for count */
	VAL_COL_COUNT
};

/*
 * val_candle - Universal Validator Candle Structure.
 *
 * This structure is used by trcache to store aggregated candle data.
 * It includes OHLCV for analytics and additional metadata for
 * integrity verification and latency measurement.
 *
 * Memory Layout:
 * [Base] [OHLCV] [Metrics] [Integrity]
 */
typedef struct {
	/*
	 * [Required] Base structure for trcache core.
	 * Must be the first member to ensure safe casting.
	 */
	trcache_candle_base base;

	/*
	 * [Payload] Standard OHLCV Data.
	 * Using double precision for broad compatibility (Crypto/Stocks).
	 */
	double open;
	double high;
	double low;
	double close;
	double volume;

	/*
	 * [Metrics] Latency Measurement Fields.
	 * exchange_ts: Timestamp generated by the exchange matching engine (T).
	 * local_ts:    Timestamp when the candle was closed locally.
	 * Latency = local_ts - exchange_ts.
	 */
	uint64_t exchange_ts;
	uint64_t local_ts;

	/*
	 * [Integrity] Sequence Tracking for Gap Detection.
	 * start_seq_id: The unique ID of the FIRST trade in this candle.
	 * end_seq_id:   The unique ID of the LAST trade in this candle.
	 *
	 * Invariance Check:
	 * current.start_seq_id == prev.end_seq_id + 1
	 */
	uint64_t start_seq_id;
	uint64_t end_seq_id;

} val_candle;

/*
 * Field Definitions for trcache 'Convert' stage.
 * Maps the struct members to column arrays.
 * Broken into multiple lines to strictly follow the 80-column limit.
 */
static const trcache_field_def val_candle_fields[] = {
	{offsetof(val_candle, open),         sizeof(double),
		FIELD_TYPE_DOUBLE},
	{offsetof(val_candle, high),         sizeof(double),
		FIELD_TYPE_DOUBLE},
	{offsetof(val_candle, low),          sizeof(double),
		FIELD_TYPE_DOUBLE},
	{offsetof(val_candle, close),        sizeof(double),
		FIELD_TYPE_DOUBLE},
	{offsetof(val_candle, volume),       sizeof(double),
		FIELD_TYPE_DOUBLE},
	{offsetof(val_candle, exchange_ts),  sizeof(uint64_t),
		FIELD_TYPE_UINT64},
	{offsetof(val_candle, local_ts),     sizeof(uint64_t),
		FIELD_TYPE_UINT64},
	{offsetof(val_candle, start_seq_id), sizeof(uint64_t),
		FIELD_TYPE_UINT64},
	{offsetof(val_candle, end_seq_id),   sizeof(uint64_t),
		FIELD_TYPE_UINT64}
};

/* Helper to get the number of fields */
static const int num_val_candle_fields =
	sizeof(val_candle_fields) / sizeof(trcache_field_def);

#endif /* VALIDATOR_CORE_TYPES_H */
